/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${config.packageName}.${config.classSuffix?lower_case};

import net.ymate.platform.core.persistence.base.IEntity;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.io.Serializable;

/**
 * BaseEntity generated By EntityMojo
 *
 * @author YMP (<a href="https://www.ymate.net/">ymate.net</a>) on ${lastUpdateTime?string("yyyy/MM/dd HH:mm:ss")}
 * @since 1.0.0
 */
public abstract class BaseEntity<PK extends Serializable> implements IEntity<PK> {

	private static final long serialVersionUID = 1L;

	public BaseEntity() {
	}

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.DEFAULT_STYLE);
    }

}
