/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${config.packageName}.bean;

<#if (apidocs)>import net.ymate.apidocs.annotation.ApiProperty;</#if>
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import java.io.Serializable;

/**
 * ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> generated By EntityMojo
 *
 * @author YMP (<a href="https://www.ymate.net/">ymate.net</a>) on ${lastUpdateTime?string("yyyy/MM/dd HH:mm:ss")}
 * @since 1.0.0
 */
public class ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> implements Serializable {

    private static final long serialVersionUID = 1L;

<#list entityInfo.primaryKeys as field>
    <#if (field.remarks!"undefined") != "undefined">/**
     * ${field.remarks}
     */</#if>
    <#if (apidocs)>@ApiProperty(description = "${field.remarks!"undefined"}", demoValue = "")</#if>
    private ${field.varType} ${field.varName};

</#list>

<#list entityInfo.fields as field>
    <#if field.varName != entityInfo.primaryKeyName || (entityInfo.primaryKeys?size == 0)>
    <#if (field.remarks!"undefined") != "undefined">/**
     * ${field.remarks}
     */</#if>
    <#if (apidocs)>@ApiProperty(description = "${field.remarks!"undefined"}", demoValue = "")</#if>
    private ${field.varType} ${field.varName};

    </#if>
</#list>

    public ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if>() {
    }

<#list entityInfo.primaryKeys as field>
    public ${field.varType} get${field.varName?cap_first}() {
        return ${field.varName};
    }

    public void set${field.varName?cap_first}(${field.varType} ${field.varName}) {
        this.${field.varName} = ${field.varName};
    }

</#list>
<#list entityInfo.fields as field>
    <#if field.varName != entityInfo.primaryKeyName || (entityInfo.primaryKeys?size == 0)>
    public ${field.varType} get${field.varName?cap_first}() {
        return ${field.varName};
    }

    public void set${field.varName?cap_first}(${field.varType} ${field.varName}) {
        this.${field.varName} = ${field.varName};
    }

    </#if>
</#list>

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> target = (${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if>) o;
        return new EqualsBuilder()<#list entityInfo.primaryKeys as field>.append(${field.varName}, target.${field.varName})</#list><#list entityInfo.fields as field><#if field.varName != entityInfo.primaryKeyName || (entityInfo.primaryKeys?size == 0)>.append(${field.varName}, target.${field.varName})</#if></#list>.isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)<#list entityInfo.primaryKeys as field>.append(${field.varName})</#list><#list entityInfo.fields as field><#if field.varName != entityInfo.primaryKeyName || (entityInfo.primaryKeys?size == 0)>.append(${field.varName})</#if></#list>.toHashCode();
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.DEFAULT_STYLE);
    }

<#if (config.useChainMode)>
    public Builder bind() {
        return new Builder(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private final ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> targetBean;

        public Builder() {
            targetBean = new ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if>();
        }

        public Builder(${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> targetBean) {
            this.targetBean = targetBean;
        }

        public ${entityInfo.name?cap_first}<#if (config.useClassSuffix)>${config.classSuffix?cap_first}</#if> build() {
            return targetBean;
        }
    <#list entityInfo.primaryKeys as field>

        public ${field.varType} ${field.varName}() {
            return targetBean.get${field.varName?cap_first}();
        }

        public Builder ${field.varName}(${field.varType} ${field.varName}) {
            targetBean.set${field.varName?cap_first}(${field.varName});
            return this;
        }
    </#list>

    <#list entityInfo.fields as field>
        <#if field.varName != entityInfo.primaryKeyName || (entityInfo.primaryKeys?size == 0)>
        public ${field.varType} ${field.varName}() {
            return targetBean.get${field.varName?cap_first}();
        }

        public Builder ${field.varName}(${field.varType} ${field.varName}) {
            targetBean.set${field.varName?cap_first}(${field.varName});
            return this;
        }
        </#if>
    </#list>
    }
</#if>
}
