<#setting number_format="#">
<#macro buildGetAndSet p>
    <#if p.config?? && p.config.query?? && p.config.query.enabled><#if (p.description??)>
        /**
         * ${p.description}
         */</#if>
        <#if p.config.query.validation?? && p.config.query.validation.dateTime?? && p.config.query.validation.dateTime.enabled>
            net.ymate.platform.validation.validate.DateTimeValue get${p.name?cap_first}();

        <#else>
            ${p.type} get${p.name?cap_first}();

        </#if>
    </#if>
</#macro>
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.bean;

import java.io.Serializable;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * I${prefix}${api.name?cap_first}Bean generated By CrudMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author ${app.author!"YMP (https://www.ymate.net/)"}
 * @since ${app.version!"1.0.0"}
 */
public interface I${prefix}${api.name?cap_first}Bean extends Serializable {

<#if multiPrimaryKey><#list primaryFields as p>
    <@buildGetAndSet p/>
</#list><#elseif primaryKey??><@buildGetAndSet primaryKey/></#if><#list normalFields as p><@buildGetAndSet p/></#list>
}