<#setting number_format="#">
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.bean.impl;

import ${app.packageName}.bean.*;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.io.Serializable;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * ${prefix}${api.name?cap_first}UpdateBean generated By CrudMojo
 *
 * @author ${app.author!"YMP (<a href=\"https://www.ymate.net/\">ymate.net</a>)"} on ${.now?string("yyyy/MM/dd HH:mm")}
 * @since ${app.version!"1.0.0"}
 */
public class ${prefix}${api.name?cap_first}UpdateBean implements I${prefix}${api.name?cap_first}UpdateBean {

    private static final long serialVersionUID = 1L;

<#list normalFields as p><#if p.config?? && (p.config.update?? && p.config.update.enabled || p.config.createOrUpdate?? && p.config.createOrUpdate.enabled)><#if (p.description??)>
    /**
     * ${p.description}
     */</#if>
    private ${p.type} ${p.name};</#if>

</#list><#list normalFields as p><#if p.config?? && (p.config.update?? && p.config.update.enabled || p.config.createOrUpdate?? && p.config.createOrUpdate.enabled)>
    @Override
    public ${p.type} get${p.name?cap_first}() {
        return ${p.name};
    }

    public void set${p.name?cap_first}(${p.type} ${p.name}) {
        this.${p.name} = ${p.name};
    }

</#if></#list><#if (normalFields?size > 0)>
<#--    @Override-->
<#--    public String toString() {-->
<#--        return new ToStringBuilder(this)<#list normalFields as p><#if p.config?? && (p.config.update?? && p.config.update.enabled || p.config.createOrUpdate?? && p.config.createOrUpdate.enabled)>-->
<#--            .append("${p.name}", ${p.name})</#if></#list>-->
<#--        .toString();-->
<#--    }-->
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.DEFAULT_STYLE);
    }

    public Builder bind() {
        return new Builder(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private final ${prefix}${api.name?cap_first}UpdateBean targetBean;

        public Builder() {
            targetBean = new ${prefix}${api.name?cap_first}UpdateBean();
        }

        public Builder(${prefix}${api.name?cap_first}UpdateBean targetBean) {
            this.targetBean = targetBean;
        }

        public ${prefix}${api.name?cap_first}UpdateBean build() {
            return targetBean;
        }<#list normalFields as p><#if p.config?? && (p.config.update?? && p.config.update.enabled || p.config.createOrUpdate?? && p.config.createOrUpdate.enabled)>

        public ${p.type} ${p.name}() {
            return targetBean.get${p.name?cap_first}();
        }

        public Builder ${p.name}(${p.type} ${p.name}) {
            targetBean.set${p.name?cap_first}(${p.name});
            return this;
        }</#if></#list>
    }</#if>
}