<#setting number_format="#">
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.bean;

import java.io.Serializable;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * I${prefix}${api.name?cap_first}UpdateBean generated By CrudMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author ${app.author!"YMP (<a href=\"https://www.ymate.net/\">ymate.net</a>)"}
 * @since ${app.version!"1.0.0"}
 */
public interface I${prefix}${api.name?cap_first}UpdateBean extends Serializable {

<#list normalFields as p><#if p.config?? && (p.config.update?? && p.config.update.enabled || p.config.createOrUpdate?? && p.config.createOrUpdate.enabled)><#if (p.description??)>
    /**
     * ${p.description}
     */</#if>
    ${p.type} get${p.name?cap_first}();

</#if></#list>
}