<#setting number_format="#">
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.dto;

import ${app.packageName}.bean.impl.${prefix}${api.name?cap_first}UpdateBean;<#if apidocs>
import net.ymate.apidocs.annotation.*;</#if>
import net.ymate.platform.commons.util.DateTimeUtils;
import net.ymate.platform.core.beans.annotation.*;
import net.ymate.platform.validation.annotation.*;
import net.ymate.platform.validation.validate.*;
import net.ymate.platform.webmvc.annotation.*;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.io.Serializable;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * ${prefix}${api.name?cap_first}UpdateDTO generated By CrudMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author ${app.author!"YMP (<a href=\"https://www.ymate.net/\">ymate.net</a>)"}
 * @since ${app.version!"1.0.0"}
 */
public class ${prefix}${api.name?cap_first}UpdateDTO implements Serializable {

    private static final long serialVersionUID = 1L;

<#list normalFields as p><#if p.config?? && p.config.update?? && p.config.update.enabled><#if (p.description??)>
    /**
     * ${p.description}
     */</#if><#if apidocs>
    @ApiParam<#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>(description = "<#if p.description?? && (p.description?length > 0)>${p.description}<br/></#if>格式：`${((p.config.update.validation.dateTime.pattern!"")?length > 0)?string(p.config.update.validation.dateTime.pattern!"", "yyyy-MM-dd")}`")</#if></#if><#if p.config.update.required>
    @VRequired</#if><#if p.config.update.validation??><#if p.config.update.validation.length?? && p.config.update.validation.length.enabled>
    @VLength(min = ${p.config.update.validation.length.min}, max = ${p.config.update.validation.length.max}, eq = ${p.config.update.validation.length.eq}<#if (p.config.update.validation.length.msg?length > 0)>, msg = "${p.config.update.validation.length.msg}"</#if>)</#if><#if p.config.update.validation.dataRange?? && p.config.update.validation.dataRange.enabled && p.config.update.validation.dataRange.values?? && (p.config.update.validation.dataRange.values?size > 0)>
    @VDataRange(value = {<#list p.config.update.validation.dataRange.values as v>"${v}"<#if v_has_next>, </#if></#list>}, ignoreCase = ${p.config.update.validation.dataRange.ignoreCase?string}<#if (p.config.update.validation.dataRange.msg?length > 0)>, msg = "${p.config.update.validation.dataRange.msg}"</#if>)</#if><#if p.config.update.validation??><#if p.config.update.validation.regex?? && p.config.update.validation.regex.enabled && (p.config.update.validation.regex.regex?length > 0)>
    @VRegex(regex = "${p.config.update.validation.regex.regex}"<#if (p.config.update.validation.regex.msg?length > 0)>, msg = "${p.config.update.validation.regex.msg}"</#if>)</#if><#if p.config.update.validation.idCard?? && p.config.update.validation.idCard.enabled>
    @VIDCard<#if (p.config.update.validation.idCard.msg?length > 0)>(msg = "${p.config.update.validation.idCard.msg}")</#if></#if><#if p.config.update.validation.email?? && p.config.update.validation.email.enabled>
    @VEmail<#if (p.config.update.validation.email.msg?length > 0)>(msg = "${p.config.update.validation.email.msg}")</#if></#if><#if p.config.update.validation.mobile?? && p.config.update.validation.mobile.enabled>
    @VMobile(regex = "${p.config.update.validation.mobile.regex!""}"<#if (p.config.update.validation.mobile.msg?length > 0)>, msg = "${p.config.update.validation.mobile.msg}"</#if><#if (p.config.update.validation.mobile.msg?length > 0)>, msg = "${p.config.update.validation.mobile.msg}"</#if>)</#if><#if p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>
    @VDateTime(value = "${p.config.update.validation.dateTime.value!p.name}", pattern = <#if ((p.config.update.validation.dateTime.pattern!"")?length > 0)>"${p.config.update.validation.dateTime.pattern!""}"<#else>DateTimeUtils.YYYY_MM_DD</#if><#if (p.config.update.validation.dateTime.msg?length > 0)>, msg = "${p.config.update.validation.dateTime.msg}"</#if>)</#if><#if p.config.update.validation.numeric?? && p.config.update.validation.numeric.enabled>
    @VNumeric(min = ${p.config.update.validation.numeric.min}, max = ${p.config.update.validation.numeric.max}, eq = ${p.config.update.validation.numeric.eq}, decimals = ${p.config.update.validation.numeric.decimals}<#if (p.config.update.validation.numeric.msg?length > 0)>, msg = "${p.config.update.validation.numeric.msg}"</#if>)</#if></#if><#if p.description?? && (p.description?length > 0)>
    @VField(name = "${p.description}")</#if></#if>
    @RequestParam
    private <#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>String<#else>${p.type}</#if> ${p.name};</#if>

</#list><#list normalFields as p><#if p.config?? && p.config.update?? && p.config.update.enabled>
    public <#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>String<#else>${p.type}</#if> get${p.name?cap_first}() {
        return ${p.name};
    }

    public void set${p.name?cap_first}(<#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>String<#else>${p.type}</#if> ${p.name}) {
        this.${p.name} = ${p.name};
    }

</#if></#list><#if (normalFields?size > 0)>
    public ${prefix}${api.name?cap_first}UpdateBean toBean() {
        ${prefix}${api.name?cap_first}UpdateBean.Builder builder = ${prefix}${api.name?cap_first}UpdateBean.builder()<#list normalFields as p><#if p.config?? && p.config.update?? && p.config.update.enabled><#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>
                .${p.name}(DateTimeValue.getStartDateTimeMillisOrNull("${p.name}"))<#else>
                .${p.name}(${p.name})</#if></#if></#list>;
        return builder.build();
    }

<#--    @Override-->
<#--    public String toString() {-->
<#--        return new ToStringBuilder(this)<#list normalFields as p><#if p.config?? && p.config.update?? && p.config.update.enabled>-->
<#--            .append("${p.name}", ${p.name})</#if></#list>-->
<#--        .toString();-->
<#--    }-->
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.DEFAULT_STYLE);
    }

    public Builder bind() {
        return new Builder(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private final ${prefix}${api.name?cap_first}UpdateDTO targetDTO;

        public Builder() {
            targetDTO = new ${prefix}${api.name?cap_first}UpdateDTO();
        }

        public Builder(${prefix}${api.name?cap_first}UpdateDTO targetDTO) {
            this.targetDTO = targetDTO;
        }

        public ${prefix}${api.name?cap_first}UpdateDTO build() {
            return targetDTO;
        }<#list normalFields as p><#if p.config?? && p.config.update?? && p.config.update.enabled>

        public <#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>String<#else>${p.type}</#if> ${p.name}() {
            return targetDTO.get${p.name?cap_first}();
        }

        public Builder ${p.name}(<#if p.config.update.validation?? && p.config.update.validation.dateTime?? && p.config.update.validation.dateTime.enabled>String<#else>${p.type}</#if> ${p.name}) {
            targetDTO.set${p.name?cap_first}(${p.name});
            return this;
        }</#if></#list>
    }</#if>
}