<#setting number_format="#">
<#macro toSetId><#if multiPrimaryKey>.id(id)<#elseif primaryKey?? && !primaryKey.autoIncrement>.${primaryKey.name!"id"}(<#if primaryKey.config?? && (primaryKey.config.create?? && primaryKey.config.create.enabled || primaryKey.config.createOrUpdate?? && primaryKey.config.createOrUpdate.enabled)>${primaryKey.name}<#else>buildPrimaryKey()</#if>)</#if></#macro>
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.repository.impl;

<#if entityPackageName??>import ${entityPackageName}.*;<#elseif api.entityClass??>import ${api.entityClass};</#if>
import ${app.packageName}.bean.I${prefix}${api.name?cap_first}Bean;<#if !api.view>
<#if !(api.settings??) || api.settings.enableCreate!true>import ${app.packageName}.bean.I${prefix}${api.name?cap_first}CreateBean;</#if>
<#if !(api.settings??) || api.settings.enableUpdate!true>import ${app.packageName}.bean.I${prefix}${api.name?cap_first}UpdateBean;</#if><#if multiPrimaryKey>
import ${entityPackageName}.${prefix}${api.name?cap_first}PK;<#else>
import net.ymate.platform.commons.util.UUIDUtils;</#if></#if>
import ${app.packageName}.repository.I${prefix}${api.name?cap_first}Repository;
import ${app.packageName}.vo.I${prefix}${api.name?cap_first}VO;
import ${app.packageName}.vo.impl.${prefix}${api.name?cap_first}VO;
import net.ymate.platform.commons.exception.DataVersionMismatchException;
import net.ymate.platform.commons.lang.PairObject;
import net.ymate.platform.core.persistence.Fields;
import net.ymate.platform.core.persistence.IResultSet;
import net.ymate.platform.core.persistence.Page;
import net.ymate.platform.core.persistence.Params;
import net.ymate.platform.core.persistence.annotation.Transaction;
import net.ymate.platform.core.persistence.impl.DefaultResultSet;
import net.ymate.platform.core.support.ErrorCode;
import net.ymate.platform.persistence.jdbc.IDatabase;
import net.ymate.platform.persistence.jdbc.query.*;
import net.ymate.platform.persistence.jdbc.repo.AbstractCrudRepository;
import net.ymate.platform.persistence.jdbc.repo.annotation.Repository;
import net.ymate.platform.persistence.jdbc.support.EntityStateWrapper;

import java.sql.SQLIntegrityConstraintViolationException;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * ${prefix}${api.name?cap_first}Repository generated By CrudMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author ${app.author!"YMP (<a href=\"https://www.ymate.net/\">ymate.net</a>)"}
 * @since ${app.version!"1.0.0"}
 */
@Repository
public class ${prefix}${api.name?cap_first}Repository extends AbstractCrudRepository<<#if multiPrimaryKey>${prefix}${api.name?cap_first}PK<#elseif primaryKey??>${primaryKey.type}</#if>, ${entityName}, I${prefix}${api.name?cap_first}Bean, <#if !(api.settings??) || api.settings.enableCreate!true>I${prefix}${api.name?cap_first}CreateBean<#else>Void</#if>, <#if !(api.settings??) || api.settings.enableUpdate!true>I${prefix}${api.name?cap_first}UpdateBean<#else>Void</#if>, <#if lastModifyTimeProp?? && !lastModifyTimeProp.foreign>${lastModifyTimeProp.type}<#else>org.apache.commons.lang3.ObjectUtils.Null</#if>>  implements I${prefix}${api.name?cap_first}Repository {

    <#if !api.view><#if multiPrimaryKey>public static ${prefix}${api.name?cap_first}PK buildPrimaryKey(<#list nonAutoPrimaryFields as p>${p.type} ${p.name}<#if p_has_next>, </#if></#list>) {
        ${prefix}${api.name?cap_first}PK.Builder builder = ${prefix}${api.name?cap_first}PK.builder()<#list nonAutoPrimaryFields as p>
                .${p.name}(${p.name})</#list>;
        return builder.build();
    }<#elseif primaryKey?? && !primaryKey.autoIncrement>public static ${primaryKey.type} buildPrimaryKey() {
        <#if primaryKey.type?ends_with("String")>return UUIDUtils.UUID()<#else>// TODO Need to build the ${api.name?cap_first} primary key object.
        return null</#if>;
    }</#if>

    public ${prefix}${api.name?cap_first}Repository() {
        super(${entityName}.class);
    }

    @Override
    protected ErrorCode beforeCreate(IDatabase owner, String dataSourceName, ${entityName} entity, <#if !(api.settings??) || api.settings.enableCreate!true>I${prefix}${api.name?cap_first}CreateBean<#else>Void</#if> createBean) throws Exception {
        <#if !(api.settings??) || api.settings.enableCreate!true>
        long now = System.currentTimeMillis();
        entity.bind()<@toSetId/>
        <#if createTimeProp?? && !createTimeProp.foreign>
                .${createTimeProp.name}(now)<#if lastModifyTimeProp?? && !lastModifyTimeProp.foreign>
                .${lastModifyTimeProp.name}(now)</#if></#if>;
        return null;
        <#else>
        throw new UnsupportedOperationException();
        </#if>
    }

    @Override
    protected ErrorCode beforeUpdate(IDatabase owner, String dataSourceName, EntityStateWrapper<${entityName}> stateWrapper, <#if !(api.settings??) || api.settings.enableUpdate!true>I${prefix}${api.name?cap_first}UpdateBean<#else>Void</#if> updateBean, <#if lastModifyTimeProp?? && !lastModifyTimeProp.foreign>${lastModifyTimeProp.type}<#else>org.apache.commons.lang3.ObjectUtils.Null</#if> version) throws Exception {
        <#if !(api.settings??) || api.settings.enableUpdate!true && lastModifyTimeProp?? && !lastModifyTimeProp.foreign>
        ${entityName} entity = stateWrapper.getEntity();
        DataVersionMismatchException.comparisonVersion(entity.get${lastModifyTimeProp.name?cap_first}(), version);
        entity.set${lastModifyTimeProp.name?cap_first}(System.currentTimeMillis());
        return null;
        <#else>
        throw new UnsupportedOperationException();
        </#if>
    }

    <#if !(api.settings??) || api.settings.enableCreate!true>@Override
    @Transaction
    public ErrorCode create${api.name?cap_first}(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK id, <#elseif primaryKey?? && primaryKey.config.create.enabled>${primaryKey.type} ${primaryKey.name}, </#if>I${prefix}${api.name?cap_first}CreateBean createBean) throws Exception {
        try {
            return doCreate(owner, dataSourceName, createBean, null).getKey();
        } catch (Exception e) {
            // TODO Need to throw an exception for transaction rollback.
            // if (e instanceof SQLIntegrityConstraintViolationException
            //        || RuntimeUtils.unwrapThrow(e) instanceof SQLIntegrityConstraintViolationException) {
            //    throw new ServiceException(Constants.${prefix}${api.name?cap_first}_EXITS.code(), Constants.${prefix}${api.name?cap_first}_EXITS.message());
            }
            throw e;
        }
    }</#if>

    <#if !(api.settings??) || api.settings.enableUpdate!true>@Override
    @Transaction
    public ErrorCode update${api.name?cap_first}(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK id<#else>${primaryKey.type} ${primaryKey.name}</#if>, I${prefix}${api.name?cap_first}UpdateBean updateBean<#if lastModifyTimeProp?? && !lastModifyTimeProp.foreign>, ${lastModifyTimeProp.type} ${lastModifyTimeProp.name}</#if>) throws Exception {
        PairObject<ErrorCode, ${entityName}> result = doUpdate(owner, dataSourceName, id, updateBean, <#if lastModifyTimeProp?? && !lastModifyTimeProp.foreign>${lastModifyTimeProp.name}<#else>null</#if>, null, false);
        if (result.isEmpty()) {
            // TODO return Constants.${prefix}${api.name?cap_first}_NOT_EXITS;
            return null;
        }
        return result.getKey();
    }</#if>

    <#if !(api.settings??) || api.settings.enableStatus!true>@Override
    @Transaction
    public ErrorCode update${api.name?cap_first}s(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK[] ids<#else>${primaryKey.type}[] ${primaryKey.name}s</#if>, Fields fields, Params values, Cond additionalCond) throws Exception {
        int effectCounts = doUpdate(owner, dataSourceName, ids, fields, values, additionalCond);
        return ErrorCode.succeed().dataAttr(DATA_KEY_EFFECT_COUNTS, effectCounts);
    }</#if></#if>

    <#if !(api.settings??) || api.settings.enableQuery!true><#if !api.view>@Override
    public I${prefix}${api.name?cap_first}VO query${api.name?cap_first}(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK id<#else>${primaryKey.type} ${primaryKey.name}</#if>, Fields excludedFields, Cond additionalCond) throws Exception {
        return doQuery(owner, dataSourceName, ${prefix}${api.name?cap_first}VO.class, <#if (primaryKey.field.prefix!"")?length != 0>"${primaryKey.field.prefix!""}"<#else>null</#if>, id, excludedFields, additionalCond);
    }</#if>

    @Override
    public IResultSet<I${prefix}${api.name?cap_first}VO> query${api.name?cap_first}s(IDatabase owner, String dataSourceName, I${prefix}${api.name?cap_first}Bean queryBean, Cond additionalCond, OrderBy orderBy, Fields excludedFields, Page page) throws Exception {
        <#if (api.query?? && api.query.orderFields?? && api.query.orderFields?size > 0)>
        if (orderBy == null || orderBy.isEmpty()) {
            orderBy = OrderBy.create(owner, dataSourceName)
            <#list api.query.orderFields as orderField>
                    .${(orderField.type?lower_case)}(<#if (orderField.prefix!"")?length != 0>"${orderField.prefix!""}", </#if><#if (orderField.value!"")?contains(".")>${orderField.value!""}<#else>"${orderField.value!""}"</#if>)</#list>;
        }
        </#if>
        return new DefaultResultSet<>(doQuery(owner, dataSourceName, ${prefix}${api.name?cap_first}VO.class, queryBean, additionalCond, orderBy, excludedFields, page));
    }</#if>

    <#if !api.view><#if !(api.settings??) || api.settings.enableRemove!true>@Override
    @Transaction
    public ErrorCode remove${api.name?cap_first}(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK id<#else>${primaryKey.type} ${primaryKey.name}</#if>) throws Exception {
        int effectCounts = doRemove(owner, dataSourceName, id);
        return ErrorCode.succeed().dataAttr(DATA_KEY_EFFECT_COUNTS, effectCounts);
    }

    @Override
    @Transaction
    public ErrorCode remove${api.name?cap_first}s(IDatabase owner, String dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}PK[] ids<#else>${primaryKey.type}[] ${primaryKey.name}s</#if>) throws Exception {
        int effectCounts = doRemove(owner, dataSourceName, ids);
        return ErrorCode.succeed().dataAttr(DATA_KEY_EFFECT_COUNTS, effectCounts);
    }</#if></#if>
}