<#setting number_format="#">
<#macro buildField p>
    <#if p.config?? && p.config.query?? && p.config.query.enabled><#if (p.description??)>
        /**
        * ${p.description}
        */</#if>
        <#if p.config.query.validation?? && p.config.query.validation.dateTime?? && p.config.query.validation.dateTime.enabled>
            private String ${p.name}Str;

        <#else>
            private ${p.type} ${p.name};

        </#if>
    </#if>
</#macro>
<#macro buildGetAndSet p>
    <#if p.config?? && p.config.query?? && p.config.query.enabled><#if p.config.query.validation?? && p.config.query.validation.dateTime?? && p.config.query.validation.dateTime.enabled>
        @Override
        public net.ymate.platform.validation.validate.DateTimeValue get${p.name?cap_first}() {
            return net.ymate.platform.validation.validate.DateTimeValue.parse(${p.name}Str, DateTimeUtils.YYYY_MM_DD, false);
        }

        public String get${p.name?cap_first}Str() {
            return ${p.name}Str;
        }

        public void set${p.name?cap_first}Str(String ${p.name}Str) {
            this.${p.name}Str = ${p.name}Str;
        }

    <#else>
        @Override
        public ${p.type} get${p.name?cap_first}() {
            return ${p.name};
        }

        public void set${p.name?cap_first}(${p.type} ${p.name}) {
            this.${p.name} = ${p.name};
        }

    </#if></#if>
</#macro>
/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${app.packageName}.taglib;

import ${app.packageName}.bean.*;
import ${app.packageName}.repository.I${prefix}${api.name?cap_first}Repository;<#if multiPrimaryKey>
import ${app.packageName}.repository.impl.${prefix}${api.name?cap_first}Repository;</#if>
import ${app.packageName}.vo.I${prefix}${api.name?cap_first}VO;
import net.ymate.platform.commons.util.DateTimeUtils;
import net.ymate.platform.core.persistence.Fields;
import net.ymate.platform.core.persistence.IResultSet;
import net.ymate.platform.core.persistence.Page;
import net.ymate.platform.persistence.jdbc.IDatabase;
import net.ymate.platform.persistence.jdbc.JDBC;
import net.ymate.platform.persistence.jdbc.query.OrderBy;
import net.ymate.platform.validation.validate.DateTimeValue;
import net.ymate.web.taglib.AbstractTagSupport;
import org.apache.commons.lang3.ArrayUtils;
import org.apache.commons.lang3.StringUtils;

import javax.servlet.jsp.JspException;

/**
 * <#if api.description?? && (api.description?length > 0)>${api.description}</#if>
 *
 * ${prefix}${api.name?cap_first}Tag generated By CrudMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author ${app.author!"YMP (https://www.ymate.net/)"}
 * @since ${app.version!"1.0.0"}
 */
public class ${prefix}${api.name?cap_first}Tag extends AbstractTagSupport implements I${prefix}${api.name?cap_first}Bean {

<#if multiPrimaryKey><#list primaryFields as p>
    <@buildField p/>
</#list><#elseif primaryKey??><@buildField primaryKey/></#if>

<#list normalFields as p>
    <@buildField p/>
</#list>

    private String dataSourceName;

    private String excludedFields;

    private String orderByFields;

    private Integer page;

    private Integer pageSize;

    @Override
    protected Object doProcessTagData() throws JspException {
        try {
            IDatabase databaseOwner = JDBC.get();
            I${prefix}${api.name?cap_first}Repository repository = databaseOwner.getOwner().getBeanFactory().getBean(I${prefix}${api.name?cap_first}Repository.class);
            Fields fields = null;
            if (StringUtils.isNotBlank(excludedFields)) {
                String[] fieldsArr = StringUtils.split(excludedFields, '|');
                if (ArrayUtils.isNotEmpty(fieldsArr)) {
                    fields = Fields.create(fieldsArr);
                }
            }
            if (StringUtils.isNotBlank(getId())) {
                return repository.query${api.name?cap_first}(databaseOwner, dataSourceName, <#if multiPrimaryKey>${prefix}${api.name?cap_first}Repository.buildPrimaryKey(<#list primaryFields as p>${p.name}<#if p_has_next>, </#if></#list>)<#else>getId()</#if>, fields);
            } else {
                OrderBy orderBy = null;
                if (StringUtils.isNotBlank(orderByFields)) {
                    orderBy = OrderBy.create(databaseOwner, dataSourceName).orderBy(orderByFields);
                }
                IResultSet<I${prefix}${api.name?cap_first}VO> result = repository.query${api.name?cap_first}s(databaseOwner, dataSourceName, this, null, orderBy, fields, Page.createIfNeed(page, pageSize));
                if (doInitIterator(result.getResultData().iterator(), result.getPageCount(), result.getRecordCount())) {
                    return null;
                }
                return result;
            }
        } catch (Exception e) {
            throw new JspException(e);
        }
    }

    <#if multiPrimaryKey><#list primaryFields as p>
        <@buildGetAndSet p/>
    </#list><#elseif primaryKey??><@buildGetAndSet primaryKey/></#if><#list normalFields as p><@buildGetAndSet p/></#list>

    public String getDataSourceName() {
        return dataSourceName;
    }

    public void setDataSourceName(String dataSourceName) {
        this.dataSourceName = dataSourceName;
    }

    public String getExcludedFields() {
        return excludedFields;
    }

    public void setExcludedFields(String excludedFields) {
        this.excludedFields = excludedFields;
    }

    public String getOrderByFields() {
        return orderByFields;
    }

    public void setOrderByFields(String orderByFields) {
        this.orderByFields = orderByFields;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

}
