<#setting number_format="#">
<%--
  _base_crud.jsp generated By CrudMojo on ${.now?string("yyyy/MM/dd a HH:mm")}
  Author: YMP (https://www.ymate.net/)
  Version: 1.0.0
--%>
<%@ page contentType="text/html;charset=UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.ymate.net/ymweb_core" prefix="ymweb" %>
<%@ taglib uri="http://www.ymate.net/ymweb_fn" prefix="func" %>
<%@ taglib tagdir="/WEB-INF/tags/adminlte3" prefix="adminlte" %>

<ymweb:ui cleanup="false">
    <ymweb:layout cleanup="false">
        <ymweb:css href="@{page.path}assets/adminlte3/plugins/jsgrid/jsgrid.min.css"/>
        <ymweb:css href="@{page.path}assets/adminlte3/plugins/jsgrid/jsgrid-theme.min.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/select2/css/select2.min.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/icheck-bootstrap/icheck-bootstrap.min.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/daterangepicker/daterangepicker.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/summernote/summernote-bs4.min.css"/>

        <ymweb:css href="@{page.path}assets/adminlte3/plugins/toastr/toastr.min.css"/>

        <ymweb:css href="@{page.path}assets/commons/plugins/jquery-confirm/jquery-confirm.min.css"/>

        <ymweb:css href="@{page.path}assets/commons/css/ymate-web.css"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/jsgrid/jsgrid.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/jsgrid/i18n/jsgrid-zh-cn.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/select2/js/select2.full.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/select2/js/i18n/zh-CN.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/toastr/toastr.min.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/jquery-validation/jquery.validate.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/jquery-validation/additional-methods.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/jquery-validation/localization/messages_zh.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/bootstrap4-paginator/bootstrap-paginator.min.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/moment/moment-with-locales.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/daterangepicker/daterangepicker.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/bs-custom-file-input/bs-custom-file-input.min.js"/>

        <ymweb:script src="@{page.path}assets/adminlte3/plugins/summernote/summernote-bs4.min.js"/>
        <ymweb:script src="@{page.path}assets/adminlte3/plugins/summernote/lang/summernote-zh-CN.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/plugins/blueimp/tmpl.min.js"/>
        <ymweb:script src="@{page.path}assets/commons/plugins/blueimp/md5.min.js"/>
        <ymweb:script src="@{page.path}assets/commons/plugins/jsencrypt/jsencrypt.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/plugins/js-cookie/js.cookie.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/plugins/jquery-confirm/jquery-confirm.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/plugins/jquery-loading-overlay/loadingoverlay.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/plugins/jquery-serializeJSON/jquery.serializejson.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/js/ymate-web.js"/>
        <ymweb:script src="@{page.path}assets/commons/js/commons.js"/>

        <adminlte:layout _lang="zh-CN"
                         _holdTransition="true"
                         _sidebarMini="true"
                         _sidebarCollapse="false"
                         _layoutFixed="true"
                         _layoutNavbarFixed="true"
                         _layoutFooterFixed="true">
            <adminlte:preloader/>

            <adminlte:main-header>
                <adminlte:navbar-nav _id="navMenu"/>
                <adminlte:navbar-nav _id="navAction" _right="true"/>
            </adminlte:main-header>

            <adminlte:main-sidebar _showSearchPanel="true"
                                   _searchPlaceholder="搜索"
                                   _navChildIndent="true"
                                   _navLegacy="true"/>

            @{body}

            <adminlte:main-footer/>

            <adminlte:control-sidebar _nonWrapper="true"/>
        </adminlte:layout>
    </ymweb:layout>
</ymweb:ui>