<#setting number_format="#">
<%--
  _base_crud.jsp generated By CrudMojo on ${.now?string("yyyy/MM/dd a HH:mm")}
  Author: YMP (https://www.ymate.net/)
  Version: 1.0.0
--%>
<%@ page contentType="text/html;charset=UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.ymate.net/ymweb_core" prefix="ymweb" %>
<%@ taglib uri="http://www.ymate.net/ymweb_fn" prefix="func" %>
<%@ taglib tagdir="/WEB-INF/tags/adminlte3" prefix="adminlte" %>

<ymweb:ui cleanup="false">
    <ymweb:layout cleanup="false">
        <ymweb:css href="//cdn.jsdelivr.net/npm/jsgrid@1.5.3/dist/jsgrid.min.css"/>
        <ymweb:css href="//cdn.jsdelivr.net/npm/jsgrid@1.5.3/dist/jsgrid-theme.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/icheck-bootstrap@3.0.1/icheck-bootstrap.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/daterangepicker@3.1.0/daterangepicker.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/tempusdominus-bootstrap-4@5.39.0/build/css/tempusdominus-bootstrap-4.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/toastr@2.1.4/build/toastr.min.css"/>

        <ymweb:css href="//cdn.jsdelivr.net/npm/jquery-confirm@3.3.4/dist/jquery-confirm.min.css"/>

        <ymweb:css href="@{page.path}assets/commons/css/ymate-web.css"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/jsgrid@1.5.3/dist/jsgrid.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/jsgrid@1.5.3/dist/i18n/jsgrid-zh-cn.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.full.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/i18n/zh-CN.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/toastr@2.1.4/build/toastr.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/additional-methods.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/localization/messages_zh.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/bootstrap4-paginator@2.0.0/build/bootstrap-paginator.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/moment@2.29.1/locale/zh-cn.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/daterangepicker@3.1.0/daterangepicker.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/tempusdominus-bootstrap-4@5.39.0/build/js/tempusdominus-bootstrap-4.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/bs-custom-file-input@1.3.4/dist/bs-custom-file-input.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/summernote@0.8.20/dist/summernote-bs4.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/summernote@0.8.20/dist/lang/summernote-zh-CN.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/blueimp-tmpl@3.20.0/js/tmpl.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/blueimp-md5@2.19.0/js/md5.min.js"/>
        <ymweb:script src="//cdn.jsdelivr.net/npm/jsencrypt@3.2.1/bin/jsencrypt.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/jquery-confirm@3.3.4/dist/jquery-confirm.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js"/>

        <ymweb:script src="//cdn.jsdelivr.net/npm/jquery-serializejson@3.2.1/jquery.serializejson.min.js"/>

        <ymweb:script src="@{page.path}assets/commons/js/ymate-web.js"/>
        <ymweb:script src="@{page.path}assets/commons/js/commons.js"/>

        <adminlte:layout-cdn _lang="zh-CN"
                             _holdTransition="true"
                             _sidebarMini="true"
                             _sidebarCollapse="false"
                             _layoutFixed="true"
                             _layoutNavbarFixed="true"
                             _layoutFooterFixed="true">
            <adminlte:preloader/>

            <adminlte:main-header>
                <adminlte:navbar-nav _id="navMenu"/>
                <adminlte:navbar-nav _id="navAction" _right="true"/>
            </adminlte:main-header>

            <adminlte:main-sidebar _showSearchPanel="true"
                                   _searchPlaceholder="搜索"
                                   _navChildIndent="true"
                                   _navLegacy="true"/>

            @{body}

            <adminlte:main-footer/>

            <adminlte:control-sidebar _nonWrapper="true"/>
        </adminlte:layout-cdn>
    </ymweb:layout>
</ymweb:ui>