package ${packageName};

import net.ymate.platform.core.beans.annotation.Interceptor;
import net.ymate.platform.core.beans.intercept.AbstractInterceptor;
import net.ymate.platform.core.beans.intercept.InterceptContext;
import net.ymate.platform.core.beans.intercept.InterceptException;

/**
 * ${interceptorName?cap_first}Interceptor generated By InterceptorMojo on ${.now?string("yyyy/MM/dd a HH:mm")}
 *
 * @author YMP (https://www.ymate.net/)
 */
@Interceptor(${interceptorName?cap_first}.class)
public final class ${interceptorName?cap_first}Interceptor extends AbstractInterceptor {

    @Override
    protected Object before(InterceptContext context) throws InterceptException {
        ${interceptorName?cap_first} ann = findInterceptAnnotation(context, ${interceptorName?cap_first}.class);
        // TODO What to do?
        return null;
    }

    @Override
    protected Object after(InterceptContext context) throws InterceptException {
        // TODO What to do?
        return null;
    }
}