package ${packageName};

import net.ymate.platform.core.beans.annotation.InterceptAnnotation;

import java.lang.annotation.*;

/**
 * ${interceptorName?cap_first} generated By InterceptorMojo on ${.now?string("yyyy/MM/dd a HH:mm")}
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target({ElementType.PACKAGE, ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@InterceptAnnotation
public @interface ${interceptorName?cap_first} {
}