package ${packageName}.impl;

import ${packageName}.I${moduleName?cap_first};
import ${packageName}.I${moduleName?cap_first}Config;
import net.ymate.platform.core.module.IModuleConfigurer;
import net.ymate.platform.core.module.impl.DefaultModuleConfigurable;

/**
 * Default${moduleName?cap_first}Config generated By ModuleMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author YMP (https://www.ymate.net/)
 */
public class Default${moduleName?cap_first}Configurable extends DefaultModuleConfigurable {

    public static Builder builder() {
        return new DefaultDocsConfigurable.Builder();
    }

    private Default${moduleName?cap_first}Configurable() {
        super(I${moduleName?cap_first}.MODULE_NAME);
    }

    public static final class Builder {

        private final Default${moduleName?cap_first}Configurable configurable = new Default${moduleName?cap_first}Configurable();

        private Builder() {
        }

        public Builder enabled(boolean enabled) {
            configurable.addConfig(I${moduleName?cap_first}Config.ENABLED, String.valueOf(enabled));
            return this;
        }

        public IModuleConfigurer build() {
            return configurable.toModuleConfigurer();
        }
    }
}