/*
 * Copyright ${.now?string("yyyy")} the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${packageName}.impl;

import ${packageName}.I${moduleName?cap_first};
import ${packageName}.I${moduleName?cap_first}Config;
import net.ymate.platform.core.module.IModuleConfigurer;
import net.ymate.platform.core.module.impl.DefaultModuleConfigurable;

/**
 * Default${moduleName?cap_first}Config generated By ModuleMojo on ${.now?string("yyyy/MM/dd HH:mm")}
 *
 * @author YMP (https://www.ymate.net/)
 */
public final class Default${moduleName?cap_first}Configurable extends DefaultModuleConfigurable {

    public static Builder builder() {
        return new Builder();
    }

    private Default${moduleName?cap_first}Configurable() {
        super(I${moduleName?cap_first}.MODULE_NAME);
    }

    public static final class Builder {

        private final Default${moduleName?cap_first}Configurable configurable = new Default${moduleName?cap_first}Configurable();

        private Builder() {
        }

        public Builder enabled(boolean enabled) {
            configurable.addConfig(I${moduleName?cap_first}Config.ENABLED, String.valueOf(enabled));
            return this;
        }

        public IModuleConfigurer build() {
            return configurable.toModuleConfigurer();
        }
    }
}