package ${packageName};

import java.lang.annotation.*;

/**
 * V${validatorName?cap_first} generated By ValidatorMojo on ${.now?string("yyyy/MM/dd a HH:mm")}
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface V${validatorName?cap_first} {

    /**
     * @return 自定义验证消息
     */
    String msg() default "";
}